org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false

minecraft_version=1.20.1
minecraft_version_range=[1.20.1,1.21)
forge_version=47.4.1
forge_version_range=[47,)
loader_version_range=[47,)

mod_loader=forge
origins_version_range=[1.20.1-1.10.0.9,)
pehkui_version_range=[1.20.1-3.8.2,)

mapping_channel=parchment
mapping_version=2023.09.03-1.20.1

mod_id=newnew_origins
mod_name=NewNew Origins
mod_license=All Rights Reserved
mod_version=1.0.0
mod_group_id=com.example.NewNewOrigins
mod_authors=gam0zing
mod_description=Add origins for newnew mod pack.

apoli_version=2.9.0.8
calio_version=1.11.0.5
origins_version=1.10.0.9
caelus_version=3.2.0
pehkui_version=3.8.2

systemProp.net.minecraftforge.gradle.check.certs=false